name: JFrog OIDC Passwordless CI/CD

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  JF_URL: https://trialzy69c9.jfrog.io

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JFrog CLI (OIDC)
        uses: jfrog/setup-jfrog-cli@v4
        with:
          oidc-provider-name: krypto-data-github-oidc
          oidc-audience: krypto-data-github-oidc
          disable-auto-build-publish: true

      - name: Create dummy DLT manifest file
        run: echo "KriptoStream DLT manifest - build ${{ github.run_number }}" > dlt-manifest.txt

      - name: Upload artifact to Artifactory
        run: jf rt upload dlt-manifest.txt krypto-data-npm-dev-local/dlt-manifest.txt --build-name=krypto-build --build-number=${{ github.run_number }}

      - name: Publish Build Info (env + git collected inline)
        run: jf rt build-publish krypto-build ${{ github.run_number }} --project=krypto-data --collect-env --collect-git-info
